#!/bin/sh
# This script is used to notify user if current iTerm2 session is not active.
TITLE=$1
MESSAGE=$2

# check if we are in iTerm
[[ "$TERM_PROGRAM" == "iTerm.app" ]] || exit

# find 'terminal-notifier' full path
NOTIFY_CMD=`which terminal-notifier`
[[ -z "$NOTIFY_CMD" ]] && exit

# find 'iterm-activate-session' full path
ACTIVATE_CMD=`which iterm-activate-session`
[[ -z "$ACTIVATE_CMD" ]] && exit

# get iTerm session ID
SESSION_ID=${ITERM_SESSION_ID#*:}
[[ -z "$NOTIFY_CMD" ]] && exit

# check if current iTerm session is active
IS_ACTIVE=`osascript <<OSA
    tell application "iTerm"
        -- frontmost and (count of (sessions of (current tab of current window) whose id is equal to "$SESSION_ID")) is greater than 0
        frontmost and id of (current session of current window) is equal to "$SESSION_ID"
    end tell
OSA`

# if current session is inactive - show notify
if [[ $IS_ACTIVE == 'false' ]]; then
    $NOTIFY_CMD -title "$TITLE" -message "$MESSAGE" -execute "$ACTIVATE_CMD $SESSION_ID"
fi
