#!/bin/sh
# color variables
if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	color_yellow="$(/usr/bin/tput setaf 3)"
	color_red="$(/usr/bin/tput setaf 1)"
	color_off="$(/usr/bin/tput sgr0)"
else
	color_yellow=''
	color_red=''
	color_off=''
fi

# fetch repo
echo "==== ${color_yellow}git fetch origin${color_off} ====" && git fetch -p origin
[ $? -ne 0 ] && exit 1

# check if branch have remote tracking and pull it
git rev-parse --abbrev-ref --symbolic-full-name @{u} >/dev/null 2>&1
if [ $? -eq 0 ]; then
	echo "==== ${color_yellow}git pull${color_off} ====" && git pull
else
	echo "!!!! ${color_red}no tracking branch found${color_off} !!!!"
fi
