#!/bin/sh

# color variables
if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	color="$(/usr/bin/tput setaf 3)"
	color_off="$(/usr/bin/tput sgr0)"
else
	color=''
	color_off=''
fi

echo "==== ${color}git fetch origin${color_off} ====" && git fetch -p origin && echo "==== ${color}git pull${color_off} ====" && git pull

