#!/bin/bash
# Convert python profiler output files to png images

# input directory
if [ "$#" -eq 0 ]; then
	PROF_DIR=.  # current directory by default
else
	PROF_DIR=$1
fi

# color variables
if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	color_done="$(/usr/bin/tput setaf 2)"
	color_skip="$(/usr/bin/tput setaf 3)"
	color_off="$(/usr/bin/tput sgr0)"
else
	color_done=
	color_skip=
	color_off=
fi

# do convert
find $PROF_DIR -name '*.prof' | while read prof_file; do
	output_file=$prof_file.png
	if [ -e  $output_file ]; then
		echo "$output_file - ${color_skip}exists${color_off}"
	else
		gprof2dot -f pstats $prof_file | dot -Tpng -o $output_file
		echo "$output_file - ${color_done}convert${color_off}"
	fi
done
